apiVersion: v1
kind: Namespace
metadata:
  name: trino
  labels:
    toolkit.fluxcd.io/tenant: kog-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: trino
  namespace: trino
spec:
  interval: 24h
  url: https://trinodb.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trino-cluster
  namespace: trino
spec:
  interval: 5m
  chart:
    spec:
      chart: trino
      version: 0.33.0
      sourceRef:
        kind: HelmRepository
        name: trino
        namespace: trino
      interval: 1m
  values:
    envFrom:
      - secretRef:
          name: minio-creds
    image:
      tag: "464"
    server:
      workers: 6
    coordinator:
      jvm:
        maxHeapSize: "4G"
    worker:
      jvm:
        maxHeapSize: "4G"
    service:
      type: LoadBalancer
      port: 8080
    catalogs:
      prod: |-
        connector.name=iceberg
        fs.native-s3.enabled=true
        iceberg.catalog.type=rest
        iceberg.rest-catalog.security=NONE
        iceberg.rest-catalog.uri=https\://nessie.local.reinthal.me/iceberg/
        iceberg.rest-catalog.vended-credentials-enabled=false
        s3.endpoint=https\://minio.nas.reinthal.me
        s3.path-style-access=true
        s3.region=us-east-1
    additionalConfigProperties:
      - http-server.process-forwarded=true
      - http-server.process-forwarded=true
      - query.max-memory=24GB          # Total memory limit across all nodes
      - query.max-memory-per-node=3GB # Per-node memory limit (less than JVM heap)
      - memory.heap-headroom-per-node=512MB # Headroom to prevent OOM errors
