apiVersion: v1
kind: Namespace
metadata:
  name: trino
  labels:
    toolkit.fluxcd.io/tenant: kog-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: trino
  namespace: trino
spec:
  interval: 24h
  url: https://trinodb.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: trino-cluster
  namespace: trino
spec:
  interval: 5m
  chart:
    spec:
      chart: trino
      version: 0.33.0
      sourceRef:
        kind: HelmRepository
        name: trino
        namespace: trino
      interval: 1m
  values:
    envFrom:
      - secretRef:
          name: minio-creds
    image:
      tag: "464"
    server:
      workers: 3
    coordinator:
      jvm:
        maxHeapSize: "4G"
    worker:
      jvm:
        maxHeapSize: "4G"
    catalogs:
      prod: |-
        connector.name=iceberg
        fs.native-s3.enabled=true
        iceberg.catalog.type=rest
        iceberg.rest-catalog.security=NONE
        iceberg.rest-catalog.uri=https\://nessie.local.reinthal.cc/iceberg/
        iceberg.rest-catalog.vended-credentials-enabled=false
        s3.endpoint=http\://nas.reinthal.me\:9000
        s3.path-style-access=true
        s3.region=us-east-1
      dev: |-
        connector.name=iceberg
        iceberg.catalog.type=nessie
        iceberg.nessie-catalog.uri=https\://nessie.local.reinthal.cc/api/v2
        iceberg.nessie-catalog.default-warehouse-dir=/tmp
        iceberg.nessie-catalog.ref=dev
        iceberg.nessie-catalog.client-api-version=V2
    additionalConfigProperties:
      - http-server.process-forwarded=true
