apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  labels:
    toolkit.fluxcd.io/tenant: datadrivet-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keycloak
  namespace: flux-system
spec:
  type: "oci"
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keycloak
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: flux-system
      version: 18.7.1
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: keycloak
  targetNamespace: keycloak
  values:
    auth:
      existingSecret: keycloak-secret
      passwordSecretKey: keycloak-admin-password
      adminUser: keycloak
    postgresql:
      enabled: false
    externalDatabase:
      database: keycloak
      host: postgres.reinthal.me
      port: 5432
      user: keycloak
      existingSecret: keycloak-secret
      existingSecretPasswordKey: keycloak-postgres-password
    extraEnvVars: []
    extraStartupArgs: --features=preview --log-level=org.keycloak.events:debug
    extraVolumeMounts: |
      - name: extensions
        mountPath: /opt/bitnami/keycloak/providers
    extraVolumes: |
      - name: extensions
        emptyDir: {}
    httpRelativePath: /auth/
    ingress:
      enabled: true
      tls: true
      hostname: auth.local.reinthal.cc
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt

    adminIngress:
      enabled: true
      tls: true
      hostname: keycloak.local.reinthal.cc
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt

    initContainers: |
      - name: realm-ext-provider
        image: curlimages/curl
        imagePullPolicy: IfNotPresent
        command:
          - sh
        args:
          - -c
          - |
            curl -L -f -S -o /extensions/onyxia-web.jar https://github.com/InseeFrLab/onyxia/releases/download/v8.4.5/keycloak-theme.jar
        volumeMounts:
          - name: extensions
            mountPath: /extensions
    production: true
    proxy: edge
    replicaCount: 2
    tls:
      autoGenerated: false
      enabled: false
