apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nfs.yaml
  
  # keycloak
  - keycloak.yaml
  - keycloak-secret-sealed.yaml

  # minio
  - minio.yaml
  - minio-tenant-config-secret-sealed.yaml
