apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    toolkit.fluxcd.io/tenant: kog-team
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-headers
  namespace: minio
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
    customFrameOptionsValue: SAMEORIGIN
    customRequestHeaders:
      X-Forwarded-Proto: https
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: body-size-headers
  namespace: minio
spec:
  buffering:
    maxRequestBodyBytes: 50000000 # 50mb
    maxResponseBodyBytes: 50000000
    memRequestBodyBytes: 50000000
    memResponseBodyBytes: 50000000
    retryExpression: IsNetworkError() && Attempts() <= 2
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: websockets-enabled
  namespace: minio
spec:
  headers:
    customRequestHeaders:
      Connection: keep-alive, Upgrade
      Upgrade: WebSocket
      X-Forwarded-Proto: https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-operator-ingress
  namespace: minio
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`minio-operator.platform.datadrivet.dev`)
      kind: Rule
      middlewares:
        - name: body-size-headers
          namespace: minio
        - name: websockets-enabled
          namespace: minio
      services:
        - name: console
          port: 9090
  tls:
    secretName: platform-datadrivet-dev-tls
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  interval: 360m0s
  url: https://operator.min.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: operator
      version: 7.0.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system

  install:
    createNamespace: true
  interval: 360m0s
  releaseName: minio
  targetNamespace: minio

  values:
    operator:
      env:
        - name: CLUSTER_DOMAIN
          value: "platform.datadrivet.dev"
        - name: OPERATOR_STS_ENABLED
          value: "on"
        - name: MINIO_CONSOLE_TLS_ENABLE
          value: "off"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      version: 7.0.0
  install:
    createNamespace: true
  interval: 360m0s
  releaseName: minio-tenant
  targetNamespace: minio
  values:
    tenant:
      name: reinthal
      features:
        enableSFTP: false
        domains:
          console: https://minio-console.platform.datadrivet.dev
          minio:
            - https://minio.platform.datadrivet.dev
      configuration:
          name: testminio-env-configuration
      configSecret:
        existingSecret: true
      pools:
        - servers: 2
          name: pool-0
          volumesPerServer: 2
          size: 100Gi
          storageClassName: longhorn-local
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsNonRoot: true
          containerSecurityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

    ingress:
      api:
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: minio-body-size-headers@kubernetescrd
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        enabled: true
        host: minio.platform.datadrivet.dev
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - minio.platform.datadrivet.dev
            secretName: platform-datadrivet-dev-tls

      console:
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: minio-body-size-headers@kubernetescrd, minio-websockets-enabled@kubernetescrd
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        enabled: true
        host: minio-console.platform.datadrivet.dev
        path: /
        pathType: Prefix
        tls:
          - hosts:
              - minio-console.platform.datadrivet.dev
            secretName: platform-datadrivet-dev-tls
