---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-tenant-config-secret
  namespace: minio
spec:
  encryptedData:
    config.env: AgA8TIx1sScih2su7KP60Nvp/scRIyCnVAoi013APy4TuDddsxHLBz60QTZcQpLBqpLEyyOzLZ3Lt3Fx5wutBxscRl/tKPGumpFTZ3CkDptbU9JQzpJQM95tdoT++gD5HtgkyIPmORqV/2XwQAytPC+3sNIUc66MfOPyezxRdRryOVOfkyQ0Y/F3DSwmE7wUVqekRYDxbafNInBYo4DnPY++RmOtUtcU/TTo/ULJKXRqM6CgS9xujf1pRcwnb6yjvU6ne4LtYw0etjzh418mvcUgQaQpZJATogEJMBeTbEz6LWz20I3GNTOXRTfNo3tEmy3VDRRSbeJXFZVlcSnwkI/1KT/jQup5dd/nwyvZF8C+Pw8uvfrtdoJs7ezzIDtMOWorpbN0TY+szGOqS9rFYDxPtFsT4VGc5ET33kzTSw/bqQZa2AMf/M3ZWFkQC0ndAD37QQzmaWiaizVXEdo38QMj+txcSD+u9vTR/E77UATwIyJFrthX0L1zOJeR73opZVaIOagrx0otXZg/odTGebGGQIwatF8/Y9OXdAYWR/pvhv5FXclWtmQv4aMAZ/5hip98hq/TlzqdJvDFLd9S9n80Wc77jRIZdMe1eNL2idfHWZmu5gmuc8YK6MxDAsls8b4s8FMo48GXyG25imM9lgE1MJ8ImPwo20H21kW5SEU8AiUvBTUxj5aPOnIfsHnwxdEWqQJa+fYSW9XZ2gVCAo5qKIskS61NMQNDV/sbRx2Y8gJvH4YRRboMzYntxvvRJRogimS17C5WNbkeI0DgiRk0h9uv11D9gv6Lzv1j/9maS947XR2bF9eL
  template:
    metadata:
      creationTimestamp: null
      name: minio-tenant-config-secret
      namespace: minio
