apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: truenas-csp # Replace with your desired namespace
spec:
  accessModes:
    - ReadWriteOnce # Adjust based on your requirements: ReadWriteOnce, ReadOnlyMany, or ReadWriteMany
  resources:
    requests:
      storage: 10Gi # Specify the required storage size
  storageClassName: truenas-storageclass
