
[[commands]]

help = "Get Coffee ☕"
name = "coffee"
command = "echo '☕'"

[[commands]]

help = "Deploy 🔨"
name = "deploy"

command = '''
echo "It's just git push!🔨 Enjoying fluxcd?"
validate
git push origin HEAD
'''
[[commands]]

help = "Pre-flight boostrap Checks."
name ="check"
command = '''
flux check --pre
'''
[[commands]]

help = " ☢ Bootstrap Cluster ☢"
name = "bootstrap"
command = '''
flux bootstrap github \
    --context=staging \
    --owner=${GITHUB_USER} \
    --repository=${GITHUB_REPO} \
    --branch=main \
    --personal \
    --path=clusters/staging
'''
[[commands]]

package = "kind"

[[commands]]

help = "Validate"
name = "validate"
command = '''
export REPO_ROOT=$(git rev-parse --show-toplevel)
exec sh -c $REPO_ROOT/scripts/validate.sh
'''

[[commands]]

package = "fluxcd"

[devshell]
motd = '''
{bold}{150} 🥞 A Modern Big Datalakehouse Stack 🥞 {reset}
$(type -p menu &>/dev/null && menu)
'''
packages = [
  "yq",
  "kubeconform",
  "kustomize",
  "jq",
]

