
[[commands]]

package = "sops"
category = "gitops"

[[commands]]
category = "gitops"
package = "k9s"

[[commands]]
category = "gitops"
package = "commitizen"

[[commands]]
category = "gitops"
package = "kubernetes-helm"

[[commands]]
category = "gitops"
package = "kubectl"

[[commands]]

help = "Get Coffee ☕"
name = "coffee"
command = "echo '☕'"
category = "relax"

[[commands]]

help = " 🌲 Get Fluxcd Rolling Logs 🪵"
name = "logs"
command = "flux logs -f"

[[commands]]

help = "Deploy 🔨"
name = "deploy"

command = '''
echo "It's just git push!🔨 Enjoying gitops?"
validate
git push origin HEAD
'''
[[commands]]

help = "Pre-flight boostrap Checks."
name ="check"
command = '''
flux check --pre
'''
[[commands]]

help = " ☢ Bootstrap Cluster ☢"
name = "bootstrap"
command = '''
flux bootstrap github \
    --components-extra=image-reflector-controller,image-automation-controller \
    --context=staging \
    --owner=${GITHUB_USER} \
    --repository=${GITHUB_REPO} \
    --branch=main \
    --personal \
    --read-write-key \
    --path=clusters/staging
'''
[[commands]]

package = "kind"
category = "ci"

[[commands]]

help = "Validate"
name = "validate"
command = '''
export REPO_ROOT=$(git rev-parse --show-toplevel)
pushd $REPO_ROOT >/dev/null
exec sh -c ./scripts/validate.sh
popd
'''

[[commands]]

package = "fluxcd"

[devshell]
motd = '''
{bold}{150} 🥞 A Modern Big Datalakehouse Stack 🥞 {reset}
$(type -p menu &>/dev/null && menu)
'''
packages = [
  "yq",
  "kubeconform",
  "kustomize",
  "jq",
]

