---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jupyter
  namespace: kubeflow
spec:
  interval: 24h
  url: https://hub.jupyter.org/helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jupyter
  namespace: kubeflow
spec:
  interval: 5m
  chart:
    spec:
      chart: jupyterhub
      version: "4.1.0"
      sourceRef:
        kind: HelmRepository
        name: jupyter
        namespace: kubeflow
      interval: 24h
  values:
    singleuser:
      serviceAccountName: spark-operator-spark
      image:
        name: jupyter/datascience-notebook
        tag: 98c2b44b4e44
      profileList:
        - display_name: "Datascience environment"
          description: "An environment with lots of stuff python R Julia."
          default: true
        - display_name: "Pyspark Environment"
          description: "Data Eningeering environment."
          kubespawner_override:
            image: jupyter/pyspark:spark-3.1.1
    prePuller:
      spark-notebook:
        extraImages: jupyter/pyspark-notebook
        tag: spark-3.1.1

