---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jupyter
  namespace: kubeflow
spec:
  interval: 24h
  url: https://jupyterhub.github.io/helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jupyter
  namespace: kubeflow
spec:
  interval: 5m
  chart:
    spec:
      chart: jupyter
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: jupyter
        namespace: kubeflow
      interval: 24h
  values:
    singleuser:
      image:
        name: jupyter/pyspark-notebook
        tag: latest
    serviceAccountName: spark-operator-spark

