---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: spark-operator
  namespace: kubeflow
spec:
  interval: 24h
  url: https://kubeflow.github.io/spark-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: spark-operator
  namespace: kubeflow
spec:
  interval: 5m
  chart:
    spec:
      chart: spark-operator
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: spark-operator
        namespace: kubeflow
      interval: 24h
  values: []
