apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ray-operator
  namespace: ray-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ray-operator.local.reinthal.cc`)
      kind: Rule
      services:
        - name: kuberay-operator
          port: 8265
  tls:
    secretName: local-reinthal-cc-tls
---
