apiVersion: v1
kind: Namespace
metadata:
  name: ray-system
  labels:
    toolkit.fluxcd.io/tenant: kog-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kuberay
  namespace: ray-system
spec:
  interval: 24h
  url: https://ray-project.github.io/kuberay-helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kuberay-operator
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kuberay-operator
      version: "1.2.2"
      sourceRef:
        kind: HelmRepository
        name: kuberay
        namespace: ray-system
      interval: 1m
  values: {}
---
