apiVersion: v1
kind: Namespace
metadata:
  name: dremio
  labels:
    toolkit.fluxcd.io/tenant: kog-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dremio
  namespace: dremio
spec:
  interval: 24h
  url: https://reinthal.github.io/dremio
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: dremio
  namespace: dremio
spec:
  interval: 5m
  chart:
    spec:
      chart: dremio
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: dremio
        namespace: dremio
      interval: 1m
  values:
    image: dremio/dremio-oss
    imageTag: "25.2"
    # Dremio Coordinator
    coordinator:
      # CPU & Memory
      # Memory allocated to each coordinator, expressed in MB.
      # CPU allocated to each coordinator, expressed in CPU cores.
      cpu: 4
      memory: 4096

      # This count is used for slave coordinators only.
      # The total number of coordinators will always be count + 1.
      # If this is greater than zero then the client and flight ports on the master
      # will be deactivated to steer these requests away from the master node.
      count: 0

      # Coordinator data volume size (applies to the master coordinator only).
      # In most managed Kubernetes environments (AKS, GKE, etc.), the size of the disk has a direct impact on
      # the provisioned and maximum performance of the disk.
      volumeSize: 50Gi
      storageClass: "longhorn-local"
    executor:
      count: 3
      cpu: 4
      memory: 4096
      volumeSize: 50Gi
      storageClass: longhorn-local
      cloudCache:
        volumes:
          - size: 50Gi
            storageClass: "longhorn-local"
    distStorage:
      type: "aws"
      aws:
        bucketName: "dremio"
        path: "/"
        authentication: "accessKeySecret"
        credentials:
          accessKey: "aQIP2SciyJY7nwkBYb4x"
          secret: "1ymFAoJpLXruA9CT690upCLgzEj4cKz1K4hEuoJT"
        extraProperties: |
          <property>
            <name>fs.s3a.endpoint</name>
            <value>minio.nas.reinthal.me</value>
          </property>
          <property>
            <name>fs.s3a.path.style.access</name>
            <value>true</value>
          </property>
          <property>
            <name>dremio.s3.compat</name>
            <value>true</value>
          </property>
