---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-cleanup
  namespace: dagster
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          ttlSecondsAfterFinished: 10
          serviceAccountName: pod-cleanup-sa
          containers:
            - name: kubectl-container
              image: bitnami/kubectl:latest
              command:
                [
                  "sh",
                  "-c",
                  "kubectl delete pods --field-selector=status.phase!=Running -n dagster",
                ]
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleanup-sa
  namespace: dagster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-cleanup-role
  namespace: dagster
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-cleanup-role-binding
  namespace: dagster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-cleanup-role
subjects:
  - kind: ServiceAccount
    name: pod-cleanup-sa
