apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dagster
resources:
  - dagster.yaml
  - codeserver-configuration.yaml
  - codeserver-secrets-sealed.yaml
  - postgres-auth-sealed.yaml
  # Oauth2 Proxy
  - oauth2-proxy-dagster-config.yaml
  - oauth2-proxy-dagster-helmrelease.yaml
  - oauth2-proxy-dagster-secrets-sealed.yaml
  # frontend
  - ingress.yaml
