---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-cleanup
  namespace: dagster
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-cleanup-sa
          containers:
          - name: kubectl-container
            image: bitnami/kubectl:latest
            command: ["sh", "-c", "kubectl delete jobs --field-selector=status.successful=1"]
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleanup-sa
  namespace: cleaner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-cleanup-role
  namespace: cleaner
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-cleanup-role-binding
  namespace: cleaner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-cleanup-role
subjects:
  - kind: ServiceAccount
    name: pod-cleanup-sa
