apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-cleanup
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-cleanup-sa
          containers:
            - name: pod-cleanup
              image: kognitiva/kubernetes-utils:latest
              imagePullPolicy: Always
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleanup-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-cleanup-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-cleanup-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-cleanup-role
subjects:
- kind: ServiceAccount
  name: pod-cleanup-sa
