---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    token: AgDSxujBlPERXoR4Nv8fdKF3K+LOYo5fCi49Y/HTIgedQ4Zinh5w0m87sxl2w4r+hs0b1EmRg1LQLK6xwrKwSrosqvvJXOygmjm5D9N8RbIQ/OdPE+AAq1bLUQw6LqoRBK6rF2qoYoOZrurQFT4dZNpqdcXHSMkVnTcTQhCOJsrD9NrhUH0OBHbUEJmOpDvn7SWPr9dMtEmTJA/yMsiCP57a1hBckiYHFtN2iRMySorSRn+iO+uJ4hAd1B9DPVuv5w6RIft4T9volIKY1Kn2G8Nyhs5wmHxAQoQ+8mVhcBKgi71729Fl+K0G00gA5DYofCVMjNt7/VvWOs9ys1aQDhilEpwtsrYS34QgOsYPz2FYUUZwyd0qHxdr/lVSamVp0kC8/C6oS9HUdMnCFsQqhQ5KMVn2wbffllQp+5v80rCOE1T50iTLOymH7TKDD5TX/QcAQXfptE7udvpVk19KCgJKOmb2B0pA8VlRhOFU589apx5PQZVH8YlJwb74LPvUpI7rMFyLMaQGIjrIh5ZFlnBI6ez/8XrX+tgBB6R93nnczERkqiIwyRvKqSxy0E7y/6AmOuYvwasueDaJIO2hNCR7LETaS9lnTQpVngS0qcjFR9cfh51/u+Pni5Dgpu1Z6Tcn1mPG0VZT8sJOWtHIBQ5TLnB4mp3OnO+fqPl0Py8mcYHbQznRsg998P93Ysiy44Iqc9QzRTBUqp7tt9D2Pp4KR9MOMenoMwMbsDGq+8WQsbgtgcHZOr93
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
