---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    token: AgALoKmTO1plHlc6KHn/KG2NvZk3i7EBCqm0nqH5u23FgKXIetnfnUiO3RgwSLfNRgyBg/qeg51KqfE1t++7kYAhgc0C4e7NZ3dsO4PKQEf9MhtSPpUQpDUHA7DbdTJJUAYppR4Uqnqk7CrBFExV8B2utYjhapLuoUhL3J3Csul4sUJRPVDcveTKV7qTKKZEJ7Sjf8UIgKqqvGuItq4saCFLAIZ6fT0sCSiZ8FQSMf/wcZrP7veBwrZJXG+s9BMTX0g0pjyaZe8LO7FsRXX3ifmu7xJITTMNtxHF9tw+teu0uOyaQheF5zr40hvo5Q4huRkyHl9q+r2FfGe6VUZ/euJnR4c9Hs3RlCbVDWrCD4l8+8REuSloZ9IE+PGAe7yH96WoU0289iivmORJRAfkB94h5NI60cV+00dtKKRMjGAYDoSJ/Rz7CXynaDH4AHOJOQSuebnDUsOnzg20MDFJF0Q6NyPKNBcTLvSNuHCDSEh6dWKKcByaud77cVALghmCsDLWJq2PFJ3NDOGEcIT4dYFLwATwj54IU/2ccUVO3LaOtCI6OcUcI8wcc+jnmhm97OKRigICXnnroI+GSotZaq11L4m5ycG7UnELiGMcCaWbYJdYCEcFtOlGW4yqpYhP5/ttqhUsJivCQDyczm/OMc+T2VtPdKWA7Bx4GCH9r7T9L2PsfIkl9JaXqYx8yvDkNZJDOLmlVhSfAn6JyhQLG0DyqXyL002Qnv3xWu4IgwqQak+5vfJW/n+N
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
