---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    token: AgBRyNTJZSe/wAAwyOLwxBGL1Z4Y4NDvfefAgH9ORqYo+y3ERaPwpMWJprZf2Sk0Sw5T3UOHc+rqfvHKzxNJVU6ium43C7hkJ2Enk4ytrNnvVvNrpy47E/Ky4qVuxc3QFPIApf45NYy4aNHxTxtEyzymZMVqk506Nb94Ua6gQAox1lQEzDmr2bvK7PU/SqE9X9V4n8AnQ9b4oUqKHqTPprR7caQpF0BhwRnRHtXxYQmU1bnel2QdHFsRG2ivA6owzkIKeAkb3uqH/fjmyDUujMnlzVBUZK7HJtnxEVXjiMUmn8uZYgpJTKlInVGfT03XkhUfuRng0aoPjXdf+aKeSibXNmNdTsOHFuYt+lAURUuMxT/UpNe/YUEy5YsaOsoyk0BiibdiE3WR0J/b3AcFjvLSsyCzEK90VZZzCoIowXG9vlOIcaYuEddPjEaRpplDfRNt+xbpNFJrSFe8XKMkeJ7m4JlpGzPqrtpgiidSjvnHjEm6EGnQ547QwxTSVLzHkvuxph2aI8FzoHuh46PgiH1rvyJDguon1jF2e9tbBouXJAVIEcmLxhl32ZV5kWU3GOZtVjDqueh8yrzUuKVj2iy7d0+vs4/odsCAc1CoLgI8paXFk8+5vbZ50apH7e0KR0KFBMj22LPk/AOG/tgbJJ8A10oX8odY7BVOQ5DT9yGrH8ulsms3qnf3FUj8A3gY08nKrM1s7A4WK4a+lIIrZfrAna9HAQKk1sJsh0Ie31MeDTJSDiw9gkC4
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
