---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: default
spec:
  encryptedData:
    token: AgCOODr4pQAv+KQUgFOwBpxjOOKc+CywpIK2e7OBcFYZrDgDFDk3MPJtykp/UsZ4bL7Pe1yqYVRxSyMiKcC7DKxSHx9gheofd3WhUFC2ffo662+qocfQcIlgHzWo8ylJFY8kRPxhVxg2UVBz7HD9NetJi0IuUGa9774G9x371xqzxoiwROCL4jZCBikg9aT5nEiyTtSYCXbrZnBYxC0mhiEm/5lp3RhAr8EvwpZkYnTSPbWOrrJsalpM8ya1ZjTnA8gMlVE2X7nXCb+B+fURjQqwXCd4GJQasj0JdiQDX/BgJt9UvSo/16UvFdXlUb6TTAwfOQI01A+i2EDnb5wAS3ZlruicAMafIZmsHVoTEQOrUpojy0NsQoj0KH/6bTy6AKF87Vh+CZwsgWYAeiOVY+B5jehA9n/IEejG9dQ/DT+ERQxW3Ql4SmcvE21m0P83vPIK7swKjvApoc87XMw2eg76zqaRJREMGOLgdxAHw8VyfrsTMAUd6cFVdJrPLpwInnIZxgx0Zx4Na5eFZ5bckF4EADxd1vUJdRjtcXgE3DG0G/1l5NVIAqy9+Xo0C/3vJuYBJPHQTJhKeNSSHhyK0IskW7QqC64Y/lIRkvLtddKUKXkGmn1Z50kn/MGJmdIMV5WxiknAIXhCzM3ZvsDXzNIw/5VjKd0y9KHnsjhQVqwqElhUZsxpqzmlIVfN+pcNu/oNlSTYkqnsg7NnYwOgCNMpJ34KHFdKh08KWUXohxV5YwRzuDziqt3A
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: default
