---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgA3pZ3uKKi00BZXUDW5/VTDTX4muYGoiBE5kKyrpDbTAFODLxP7HhgcWl5zYUIV8oyxnYPezFXfNKFBSvzJFs2+1YS2LnAAgWodqynKgwAaZfciJqosiRUZRptOpouvGyTSDgCm+KCIx3kZsWm034paIOYrZn1WkM5RxV2k2H+5O38tFCuMjYBzh/RVCBCHcGakStBYts5QT5TU9qUtbdPHgxhH2LQEwU29fns0pZETiAewedbeGNRhzqoCxbvpogL2ECfhK7AFodRfl7dC8FLlEaAKmkDWN8wCZ+erClKC9jObWZksFHUxiYYUCst55RwYDNfSjnhGi/0Jo/AdOcLRdj/HCLm4tsS25oaE3sC3nedGPf6+J1JFpk6oTD4j9PurTrhXy71U3VRSN/WPPIgMopW4lb+RFvAgdO3Ppo5S3r/gZ4ZuUq6DN1ZUqVZ8lTRV2nxcSRTHt5pDyfmE5h4GE0ZhEC48MkTNPRY9kVjLrYO8tHPbtTYRYlNF15ByyLBII5/r++R4Nsifqvg1nOHRQmeV1kxHksOr/Yw7Xhk7ROgIFWykMXVaAGGS2gHGo9NjEvd5iprrIezbYsvQuCytur0zrhiq2C//H9DshA2XMGkx395YebtKJyMxnLdryusEQxL4evSQCt/5Tpnh1Kvd/6iebtgp0qsR2tN0kt8reZn/g+qltnIXnpQVb9o9ED0/9UT0RE166Db4GQnnwRUr260JSkP9cRSylLMbKMyLYQSxdH/yWKlVDYFpAQHniEHP3HqfuNEc6YT/UHVYMezga9ENgsiJAWdKe0iFsvGNAC+vG4fLys1Y035g8BeYMuZp7sjankNGaXdy52fqYw87nnZSW7fSDl6+Q21wWwBTPcQpeqiQgt9Ya0l1KkFxOrqST0My9e+WOOLSWi0AJP7w7VODg1WcS/00TXiPlxbuqB7gG7TOHssVt8sLH+dGaPjhwhdkQVZMIkov
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      creationTimestamp: null
      name: ghcr-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
