---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgB2/nVLijEGi6Rj8euzYwmUKmphwLUdiIpdNqCCS1zys3NeYpl5J+ZoCVGOyvDPKUrv4t7+6WyMCMqMLg1TwDyskW7cN4QOaiO1exGKh4Gdu4CH5KZ1r68LIblsOviABLekyluc42Pmh3MLmwhKWrIEB0Ed0uv9j9+NBXVxK14kEw8upORZdKiUuzjKdESjwALIS858m2BGuDIufTSU08dFJ75yBldfFGoLJSb1n3XDh9IPYY9w4BuaVlqWJup82LGL8QWYrzCTc//8smVLCFYDqA14+4uOMUV8pIiFBx4LdMKqN92SSqNyn9cy0waNRbcaWoudlpbajF0cgH5FzSq1xM1CVlIlSvOCzN+3owSnQOEK2P05TmXxwanwzXg6p8Nh+UUYBC0l7mKSCcCtUDeWoEa/adcWiAKTsV/MjrrpsqLKzuHXdHthvKaTzvjNEzwKXZEIOkEYRWZAjQf2XehckcNA343Tfk6POHsRoboEwLvtTun4xGKCnpUpP80xrCNq22AjsRzA3ZLspSZLaiSfctwkAZrpD1bj9O4iGOhDK0whPOgFpmYeNXa7iQEyWe0OlQRdMqSZZBFkaPw19NXR20vSagZ9jd/AIx8oBLWg7HdaPpkSQqucFUd0Ol4XYbPFZtoYA60HiIbRpifdyUxYfhXE7Zb3vpG1NIPyGDO5SdOlK5/r69nmp8R9dqEwCdc+RQCuOhJEMnE3/Lnsduw7OJXnsSxpLMCMpkyYBmgSKrUWER7woDLTgyefIqKo6hHPCqLLv89FZwc2A8J99SK/HxnEBhECrbB058KJud8UIB8VOjGXBkuWCly8B7foyCeCxXz3HDliGjKTuqn0wJQZ/ZYht8lFqPCXnBFQUyo/pvxRixY+k/UtI7z4nEbqFGDTQKehkeRSzKo4ZxsSPPmdgzHwX4oALB5OI6BezhiOYK2ybJr4cWOO8D1rYujlr6Bnl0P/X/cdwMWf4+whqdzi9s+X3RkfFd+7lom1G9+kDk6gNmc2rdsfG+el35mq76hyfktBeg8dXf3VwotJNroQPckIV8K6pk15ddG5h4Fm6PEsOEjr31weLmu9F+Mnm6tpn5s6jexyaGfiWAtia/J0WLC6oG001rVM1mqoyM1kv9ydbYM4xA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
