---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBdQgV5trc8YJJ9K/GoDoymwz5tqiIbw2NIDvnOiiM98hu7uppxwbuOKiTbMZVsC2IkbshVJKOYxifEJJM+fcUOI8c8SshydVjBKFF6Y4srmtCslD9wnFKVq0r0J3yvU/MoY1dKxuAvb0ozWmOGaXqz6G7LHgE5x8wWCgHheqXiMrtB5n13qtK6D9Z0K/e6w9cl6DTiZUlPvuyQArBeOJ9LrvrihnBM9RkBT4xEYuqPK5PkM0SgtSQ8cboIy8dY4dbv9emtJt2tzUb0BHxe1ElXQbfnqT2rQdF57CZFaOs2kwzZC/Dm0MD8YIMrWEfZy9Xald/lNSmYSG4vjNHfwJfFUd0DWZd7JVDbM9l8jlSSY3sx54K6hv5NlZnucAaGYdlGVIjz6tsym5oC2zLR2/lHH7ueGTllrl9T1kCI1VNMLg89N2r/nVdYBauHJqwaH1YfLLUXZEzzewHQLMUyW/vE7ExW1hVVFMXJP/hdcmoKGlBxRa6eiJnbBRleKOwbQ5oV+lbgpVp0vpRfGVLspYKA0/BQUZTPQz3mci+xz+zpZgg5k4irL4C5JDKdKtIGdDVjCHiW7sSXgJ1wLyikFvbQcRZpTyW8lI8bVjbMOuORo/y4QRLOCXyW7dzhsOnF/7Oc4SugTCoAq+vNBCsX+2/DJPjb75b56RPfLazD4Pn1f90mfmHvzWWDqD/53UclTABHaK7OghKpzeL9xQRpe3YH32RtUDwIHfxlyL8j+2aUU/DvqQkncJT1sGfapCVTadgEW28NUssuOR03M0lCg7gFd9KdHGzQVzCjCR7NjLpP4QMUmkA7/fwfmfHxFHOqhoPbPeJSepAc3Sq1TJpC8IqwLWi/zL8nmR1n0QKiGfQ9QyoZXWdT9mxinODvI4eSLOu6QS7VKbyD3BY62ULNeIfgXtKEYEIN8JpEd6rSwcO06DtflFxikllg+Pc9HmcxeZA+otYPcFoj2eZq
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
