---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBWBsdNt0FjaoZlEGlDzR+ood+ydPHHn4lzs2G9tD4mHed5UMRoecAVDnImLPG+RQ/PWlP2SYVf2Xf9I2Ds8eUfdzSt93P4pSSmLEeJxY1MnPJyu+91TObNmZM7SaZbxNGW+rXkpPo0s5+3iMNKSU5yzcvzmoCUbKWoea4fkvDQUFOlJcEd0+ClsKwEoz4MORuddCtKxRc87hPAw15QI8b3MM9gZSc/jvngKkPrrywUtx03zjjPtUFNkU54JW7zNDocakSPaVIJTW9i/3397unhlWD1Nv1PhYLTbG01GYmshdu9zd3/Y5ZbsVKKICxdE8TvMYslKLATPj1QTqbO8kpmmhffjEfekZIvrDRMBSv9j0FTj4md2eOTxDltiFO5VSPakQcIiOUAn4iB6FjKHaGM6s0haDa4/m7hs2Ml+1caI5uKP8JDk1ANIfHCmMbMqkNNSZdE/leIbEbJMPE7QdPvux2Xlrt030DZBXG3uP9MaDh84aB2T8e9LzDp3eN9qSPjk5G7JrVdmrrtxy+K6hzYF4+CARi2wbLvHQSXfLj6jXzY4Ia98f0Snh9XRTbMU2z8He7gsGEEI+mNDNTIh83pEVWFy0fs6de0wKMy9ih4sGjZ0b0XT8lRZBJsmCQBgaF870ymAm8wfLxnT7zdIkgPFv2mZCVvz9KClsQWQrcZk/zwWy9csnUdn1WqVWzSGIDxEBHwy777aXaKo+JwcVshNN+0fFVpr5TPBbQWlEhnF5vrBz5GbRyn5OaPTRY4UKnbacZySeefNk+SlBSnDNDj1bjOvwU63VLhG5+WrjLkt5yRR0fbF+xCtbh3W8AyZtGpv0wIEDCJfx9jjCYLBhDRnBa7Yx3IWaT+eErljYIDEd57oq9/EJeM1AZzqhSHQpHm79xPLt4vdh996hvO9aYFwfReODk8VkXirKuD3eNqfjrGSyAhwLw4onuVu03N/PFxzYV+npiRpMsT/+24mmGdZ87v2V9Ro90Jvg67pWKYIoRXOw4Zt+W7hJOXeQrvd2JuPMElTLKVmAWGXdiAvwT9ean4rJlFDYpy1VJFMg27oSjF038UrQMFLiDqAVgz4PvcunnfkKbtJRyaMdJ9N7VxWu2kzhY8scO/c8aPqVq1h9bSuGWh9g==
  template:
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      creationTimestamp: null
      name: ghcr-secret
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
