apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: howigotpwned
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: howigotpwned
  policy:
    semver:
      range: 0.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: howigotpwned
  namespace: flux-system
spec:
  image: ghcr.io/reinthal/howigotpwned/dagster
  interval: 15m
  provider: generic
  secretRef:
    name: ghcr-secret
