---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-secret
  namespace: forgejo
spec:
  encryptedData:
    FORGEJO__database__PASSWD: AgCBTMi961h8iDd4aTcbA8Q6O3hg19NomlQJvMjL/bOyOcp2ama6YvtnLYeho5HZ4ZmK/Yo6MZPbcbx8pcCmo3vnUvn7xy6bML0W/EtIBPvegNoaSSzXZVCNUEaEm6K9XOTCIXKgGVwh0PEgL4QSvusKLjSFtPTuL9WFu0K2qgqnUBRmlVJJq8zd7xY02VRq4pq4QdEcn8k/iyKMYBEYEqwP3JTN/7GP4C6smE0lrTFCcbLXbAFylVg6ucvjo9DeJq/En8/3IklEQBGjqzAery5b8Ye78Th4uso76JZkg1IHjXMIaHJknTt3qWUS0En9+384ArGcgTC9zg61Q8Id0h5FNlvZdgqJDYv4D4W0iwM3QP+jbNPoG7fkyPp9UrfjMmFHvFGFlA297a7IkNBMZJxq8bHDlXQAEd1dffwpKxha4WnqdZh/ocKl6BouV/aT7n2zPfioAhkt6EMu4idNCgAG3G99XmSplqtKPHkW6oeIXDM3AYVt+AGG+Wekqkd2PxFRl2vCSdcnclXFKSCnihLdSen+g2+PZFPU9ryr9o3kQrANhnih1aNjJ2OSblGQOZOUGp30UMY6gRGDdRogpXjVMMa+gk8BGciFJecgLMdIZVRc9rGOzBZJlGmdZxqc+gxvcexMsCkxqyR/IPDxJ/1vUk6HHM2BnPa7sqYoMx8jDMWl8ySzfyKn96uOKnpGWBwOFkTKckddbLf8AqIAe+w=
    postgres-password: AgBMI3uTtF8IROLlraO7gJJDBulWcaA+DxftBJKRGEJZ13QWOPo1jM1lxsZJEIyQCwHXEVYm6Lc+LQLALnKN351Frhod/hc/98IAYnBLDdtbfhq+TzZdw9H+4ilC7385ZK88OIJAH83/+fT2prf0KjZgYycrVTkD39/3N21IxZ+zg75qTrb1Qe+pFMlTmig6AsIF5HKqLwJBBkAAk+poNGWFwIdSnH7KQVB5gqXpHl6k4vp2z3axMDhY7PyMoxKWksGXY6sWTbuMv9+xdUMENfImf6nYOTqAZxl9iv0ISQeRrxv36Lx9lUxONe5FHCb6Rtju2La4j0VC5AVa5D4uVs+P1QGo4eXttFQGm/wjw2yQJ1qzj063U22trJMRfEXl84WyFWIiPavXmMVI4B2umEbAylIesRy21UEnwd3oCUj9fTGFr9eXLjKHY/g44MoGJekfoETN6grtBSFKHsuhUwy3iRlzyCOO0gW0XffKpvq1wS1mg2WGXC1vD56gR9PeLYZgp9YFUlekQSrqEJlJyR9jrFFfvsQanBBm7HoaiEHrZUvRk82HrcxHd1ufWPTBeoXvaMHwgbFUzUApzFl52aJLUg3pwRayJ91SQlY47tAhZjPJMN/SglaE0DvbbJVA9rZcKzY4ifWS0foSo3M1UoYPw1y/gUlwXaHbLQossVuMEZUO0eYfBJz5Tg8fEl9Qw6uoK5qTEJfurCczTu6eyvo=
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-secret
      namespace: forgejo
