apiVersion: batch/v1
kind: Job
metadata:
  name: nessie-gc-job
  namespace: nessie
spec:
  template:
    spec:
      containers:
      - name: nessie-gc
        image: ghcr.io/projectnessie/nessie-gc
        args: 
          - gc
          - --uri
          - http://nessie.nessie.svc.cluster.local:19120/api/v2
          - --jdbc
          - --jdbc-url
          - "$(JDBC_URL)"
          - --jdbc-user
          - "$(JDBC_USER)"
          - --jdbc-password
          - "$(JDBC_PASSWORD)"
        envFrom:
        - secretRef:
            name: nessie-gc-credentials
      restartPolicy: Never
