apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nessie.yaml
  - postgres-creds-secrets-sealed.yaml
  - nessie-gc-credentials-sealed.yaml
  - minio-creds-secret-sealed.yaml
  - ingress.yaml
  # gc script uses virtual host style  bucket lookup and i could not
  # ge that to work with the truenas docker deployment
    #- cleanup.yaml
    #  - garbage-collector.yaml
