apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nessie.yaml
  - postgres-creds-secrets-sealed.yaml
  - nessie-gc-credentials-sealed.yaml
  - minio-creds-secret-sealed.yaml
  - ingress.yaml
  - cleanup.yaml
  - garbace-collector.yaml
