---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: nessie
spec:
  encryptedData:
    accessKeyId: AgCSVNIGRSwfFi/mPhvXrZaO+dOEmBVEzQTTJaQaVin++60uR63NxYu6NwuL8wcgJph8bUo0NoAHGJ7JA1JDBVe8pObfV35eR2C8AUR1WcWPbCpgDzvffB1XDGwAZhbig1WuTh2CW54R+QvEnrTaAtGNEGqNqubC1SBR87Lb+4E8Z00oyO2NLJNSqVBI2vSNFcZk7DqXcvEtKyLCgA2DGDq5w2Tk57tmsMYYBmf9rQukjwc6QWRmUL21qB2qHAwCIb8vEOcaQvzmeNOSxq+fPwvIPcP5lVdHO9j5hkRhgQIRZtiqoVP905180m3K8IYB8kiAMwG9LO/wzqcSWngjL5m/VtcecUq7Ahg0wlS3MW4vuscgoCyWZ/aAaI2j8OsRbROrBgScJCDWX6oR3RBymAqwvJ+mmhIziKik4Q8aOjLz458HyAE5KTFN9CRldblxh4B71p5GEVM6QY9MUBqjVDRhhltjRk2/sZIbL7Y1sByPZh9Sfop3zuex5akdGey2J8PKoiizY1UX+OumHzjudEyhbgjuGtLa74GciDD+Ng29JBkiOxZUwQe65v7mSTsghZsfhz6YEMOB7KN+VX3qa6i6R/HmlQq0hHp0qieb96/TNqq3mg64C44hI/cWYVdeSRjUwhMv5BZ5GABWsCWldUaIChKVZovdS1W2SWgKCiUY6dOhhIPbFI+iLsd+JNDBCj7xq5oQjzHwf2RfWpUkjpazo/RMiA==
    secretAccessKey: AgBBgdjwgh0Bg12qvUIbvU7PUYHSZXwH92GWkRIqlNB9uC8Qv6za9ak+Kbt5i493ZKEUwLJvUjaGrOuqRo1TeJWIlqs94R7S3bdygQGI4BVdQWDl7fWiZErtedYsCb79iJCFwaecUWkqzWKIgGKTwr0fIiFlJ5pq10SPIZy9kc59iYtndIYDwu7q45BWX+1FzTDrlJBx8dZgaBhmMB22tKh/UawHU8Iw13V/YSI4lvuYen2aa6IFMQzYfDw0iLLCGlH0LBSyEMqCOZZgwdvuUOGDnW43ekcqhGMllHlh4Yd7h4NRCeIJ/iFlTL45uMPjiuTtqb7Np+VxqJsC9UOiQnh8E8nf2hzE8d7sK8yIlRaC+kqBPSl4BU4tYAHufN76FEqYkPsJmqzHNg+bwKWkmnlBNdxaDtnu12Fwd2r2r/N+Hq6hdEzazLnP3VRCy9ag9EmqNWTlC1sMyY6aALXNWKHqcilc84X96j4O3GMT/jZMqoaVkoXyh6UxgDSkgCBmH7MiUNDsIJTVtym8+buxsNzFeph9dyAo2cGCWliUA874/ZQl3zO5TK1xHjcmlmuxGiP2WOLfMoEu6dAz7zQpWfAbLnXpd8fKu4BUd5lZ/SyJNbT/7CIphex9IKa/p8tPcB1lNcqYIvqqNU+aKEyA+rLfxZ3VZ3Nvd/ueCJcSLhDyNBYD+8jcHBzmMfvMxVS243n14Pfg7RLDPP3kYYU8HvpURFtE35XzuDROw7xqwsSHXUU9rJr0luYf
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: nessie
