---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: nessie
spec:
  encryptedData:
    accessKeyId: AgBc4LHQjb2RtitkQAd4/X/4A8wAiOy64gksled5b8YzF3wL9cnk/IrsyZ8y0aF1Eb679K+g8nsJshl3WKYi7/b1cFBypqXK25GHBUD+Ud0ePY95IyfIfe0gUKxyPdBrNG9sDw7HYh1DMU8muADApV5sQVWuek3ENQXImWBCFGWtYHhNqXkt15gpzLY6yxu8aw8AS93yQzsrCQjhIksXP9ingRYRS5pIyGiRoJ1RfBFbtfq8soGq2lkN+qvtyao+62tzYXmcysoNOQPpIL0+dw1Il36STPQcD8XALvrCD8CRsyMOFEop12sMDVehMFmeBiuz3bisTFkR7cInu5YBx7p5KdcOlU9r/hdnmERM3LvSJk2md3eKNl9g2GSqnPvumzlcauAMYAtANGm+LhTS8cPkaHoWYZx71Jv75cmKaMwdevkfG4+3wCsZowNK9pPjtXkEXX+HtXMWsX7WUqq0JSiJM+LktvqykZk1OWnaasAkL+5SglcfmctHFyUMYb/LJBxFK65E+unDlyCA7VUnUp8uL+i0iEiLqD6on5Th4aet8PgB4wRTa4GjkvTq2sLdMgi+ALWOPZDcdotrpF85fkQ9M9NvPToBB9nOuU47SJhgUckO1or/wa7nmHun1MnGFhUkNIZSKNC36kvsKl+9XICX1znQrKguiiceKrX9A5x34xsEWpck+eOZ6gAhncVHlf4UCOnH2lgpLDkOOiJwD9SdcGIs2g==
    secretAccessKey: AgAjSazWPCdk143tGaU+gevTxyLLmaloqSc9JwfdaBoDSiQYU53XDO1tHKSMrufkLZ9mq4xLcuB91L5Xq6HodataaF7IXTE6L1Ru5l2Tg20NgS4SP9Ms2e5ZY8XuKyEd+pTPuqqlEgAVv3wovprxb4Vs6acw+vRP05Eeyj1yahs0p6lnnGiCYRf4TMIGDv4n2gHBHERCEZSOcpEGbDe9BBcCsTcbOPV4V6c4kglBFTR2CwCr+kj0Hr+tIurZqN/JbnIVu1aU+5cP5imDG6ziFhvNJlUX/rTbaZC8OiFCeEylXyhNTrd8DksA5Jvac9dUnGHv3X2eT9nrcA4skGWZhGxDgGqIPczPTuyhFs4cEIAShHT1TISFD/qnhc55N8Kqngh2NRlYUNSATLhcyiJpQ0nS1gXRE0HMZcQ9DFGNDkAuhmcw8+6hQMuEIbwRJb+N1MO3a1UBgZj/RnztyVsoOg4GgoW2lMRW0q1cl7DC7qTo0nEr+/q99QnjXNbQfmAlpHpZn82nmkkvJIxijqdbV9Xj0I/YGOmm8QI0y4BT/IdeYW1zdUWrHq+T5KuUD5kPL7g1X7T0nTD/27hPqBjxG5pbQ1k8CNoKHmfuixFQfddDiF4yCXWgc5cV4WdlwoCf9vhaPEWt/TQ8CPWFhU886NotvK+aegCoJpBxpE/N+eCdyItOBpdYRQK3dxP1eaKlbcd3gShZfMRkbRE1LSnGYc0zDT3/PSceO6nX2ZzE46Q5t/H/hsrZiNRF
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: nessie
