---
apiVersion: v1
kind: Namespace
metadata:
  name: nessie
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nessie
  namespace: nessie
spec:
  interval: 24h
  url: https://charts.projectnessie.org
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nessie
  namespace: nessie
spec:
  interval: 5m
  chart:
    spec:
      chart: nessie
      version: "0.99.0"
      sourceRef:
        kind: HelmRepository
        name: nessie
        namespace: nessie
      interval: 1m
  values:
    catalog:
      enabled: true
      iceberg:
        configDefaults: {}
        configOverrides: {}
        defaultWarehouse: "default-warehouse"
        objectStoresHealthCheckEnabled: true
        warehouses:
          - name: "default-warehouse"
            location: "s3://iceberg/warehouse"
            configDefaults: {}
            configOverrides: {}
    storage:
      s3:
        defaultOptions:
          endpoint: "https://minio.local.reinthal.cc"
          pathStyleAccess: "true"
          region: "us-east-1"
          accessKeySecret:
            name: "minio-creds"
            awsAccessKeyId: "accessKeyId"
            awsSecretAccessKey: "secretAccessKey"
    replicaCount: 3
    versionStoreType: JDBC
    jdbc:
      jdbcUrl: jdbc:postgresql://10.22.21.11:5432/nessiedb?currentSchema=nessie
      secret:
        name: postgres-creds
        username: postgres_username
        password: postgres_password
    advancedConfig:
      quarkus:
        http:
          proxy:
            proxy-address-forwarding: "true"
            allow-x-forwarded: "true"
            enable-forwarded-host: "true"
            enable-forwarded-prefix: "true"
      nessie:
        version:
          store:
            persist:
              id: nessie-store
