apiVersion: v1
kind: Namespace
metadata:
  name: nessie-ns
  labels:
    toolkit.fluxcd.io/tenant: kog-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nessie
  namespace: nessie-ns
spec:
  interval: 24h
  url: https://charts.projectnessie.org
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nessie
  namespace: nessie-ns
spec:
  interval: 5m
  chart:
    spec:
      chart: nessie
      version: '0.99.0'
      sourceRef:
        kind: HelmRepository
        name: nessie
        namespace: nessie-ns
      interval: 1m
  values:
    replicaCount: 3
