---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: nessie
spec:
  encryptedData:
    postgres_password: AgBjRdyVZk+KHqFve+acuY4Wr7KDC4qnxg/kmyCGcLFmJhTIkVShZjRA/kqknUUtfD/8QVy2H9S6aaxm4g+Nowe3haMJgZsNwVCRdJ6UODxjrlKTjboXX6GmSQh7O0dMU/CPCVcYw+SSD3WRa6kZRYMvKx/cci7L08utmixFmwMBXR2cQ4OlmFK2nSV1JI69h7cINbiLXAGWz8va2Op+ilU0cjXT+btdY0F/98URIuODNYYQ7zyIv5sYGoi0xPvaSB7uuVsLwab2JZf9TY/3x9GMkVp7QWshk4jtbykU8KoqnjuiF6B31zabLaAKzd17+a5RfihgrA81li2CA34gDXF7UZokf/SjpRjOplkqelVBqiw6mf1z/jRZ0oHKuNLcbr1cIwIhIf/+MmX6Ejb48m9e/Q8qRR5vxZJga6jOBn7C8GgPVML+XVCTWwl3f9VH7dmgQTiz8X3d8l+eU+3lfpvYDX3dP7JcxWObhoEDIRjXeWjV9mDrgPcVN2JtJ3krKcyd/E+b2ZiQON9y1rWGhCyt+6N1SGEkwt7rsaqPdUUdZJbSzHuyMYl9mRgCUMDCMtJN7aKlCh4/fmHCvbyNn/+WGW1l7YCGRlbjiS38CYxBdcp4qF92y0rjqiAeIWKfJP3W0qRMH9E8e6SC3BWSNwUBJTSI53rkUssQiPMCMoNZfvDguMb1kdnm0b9orwbgqWvVONjAwFIiWe30xpPfjYc1N04ymey66WdQ4do=
    postgres_username: AgBnKS03SBrTEJfApPvk/pysmMmnQaGQlCkJIoQrpRgFnmzMCbwcLruHbpp0gM3KNk46arBQpoaDiQ2UD7SEjGzwlBmF1UtWv/dK8fh5LVT6L5FGvLpxL/UXaACmin7hZwUHFgTPBUxIWDANDQsLNJ4irNw7RpGlR80ELxkkEfR1CL+kLz7sLqHxHkTrAF7cCxwG/afOBm14fnZIa+Kbl9y0GLIQQaGEJeokbKJXXQli5BADGBVbeWGE5NJLVzZDQq8dkj5zXJeFlKUVOOdqvz6JvanElK2jTzvHk0OJ7sbV1AhFSO00dyosQ2Q+6todznSvZJZKN3/eXpB+eA1DYpmf+UaecmwJJC6V+JZsGJjYmtxyIuBSCeKsijlOBaWDLI+c4hzkDEXBjLm/WzUhtef0M17GOP3xA4FBcAvdA93iLMAD6M54a3DlAbYSoepOnATcYnGcHZ/1r0h2z8CzUELHT5YqLDyw/5UhFABC25QfUXHZ4xLz9G+n+k/Fe49dHpKWHY7wivfEzUpT2DAKtiXHq3u1fyxWyM2PsZUPjlVrgiCLRaguRUBd2tUgZdz7AL0aFfC4bN5v6HufoQvVnLpBuTpLfo4vFCXimzw0Pa1tiquS8xmJVvXbaXGiqsWv8cLoWBhpSlki7smJt2oHHmpy0APamxAztaEPS1GTOfaGzMeaViKiAg6NHSP+Ya9FqHwSnp/+Gb+PyA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-creds
      namespace: nessie
