---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-creds
  namespace: nessie
spec:
  encryptedData:
    postgres_password: AgBMnje8zpc+pMEGxeZN8YY/EYWLABU0X2HSdSH4I791GAyxKuwQe+dnSjvq4gRsn1ZfhHA0ZyrS8NR8iicWPLcmPs+E7vwDFp9set9o5Scc72eZFCcUTwEmVLdpmt62rWiO7CvOTNXtTc46+B39UCxKxrUpCCGDR8kgOeaDMZWLbTmBZobaUP7Rf7YGBZC+nwpnsQUCB63RaxgKzFkO+DbQSfBJUJGX91dYG068/DxKk+Wll3yEmOOf6D03Bh3maO31jld4pzpF7QNnbxZRiNxxx8IVfpJXirw0eOKul6JSU0a/XWimMZtEB7DqEuRyOv+EWkJ72VVoayX1ypCjdzAy/3KysqXOTXzBwvfMAS2WeOYxG4D3lB9GciUXgPIQkCFfpTT5pImZ9eegS2tiWP7x/G66sYv1iZHiG+xTpl3Tm6gekQreoGj/F0+lZ+L41HC55RFbG5cb0eJBtP7VloE0WrRW8RfeceL2rTpfVGkq7YCBLQ6G4hxnS6q554ZDsyg5FIem18DS849jDtOfceT0WMT5kX9cnOfDlEOnuK+TEMW4srFIuaIBNilQl0mV36q3cX8EzV0PasatCeh0x1zhVCxH8r4JydKp9HeZiZZRmH6A1n1sU4ZJ5ilK9SAmWVQwFYZ//MjVuPHdAQivgcrR5+UJNRwHfXLAsMnpIvaeBFi1EfaFvOxX37RV6KwC9eFpO3FjVHUMABcwhVrqeqHwAg==
    postgres_username: AgBwSgnGOVFltx+S8kIhvzogv3xOR9+PldfPg6RJUznr/ZWIWzQyp/FHAJvokA3hio6UeZgYqF08YAwQBHXYVmfJlWOP96dGwZfR9zCa0BSE2yC6NJ2+iVRSxXDPdvmYtYSM+LliOx7Xem7RaNsIUsT3/XtzJL+Za74rd0+gzDAeyJ0NrDtgo7EAlwAG8A0pq1nBUyIyqHjbhqVEQJqIgEh7ftYTjnz66Hd2MS7fbMAXrSYPsgFdmZk5bWnD7blXbaX9aVqp9jxR9mftbEeHdh2YLKxe9ELgAsXdXN/PzHb5OUK6EfM5PQc3HlRy2dwcBEY6VLGiikTHXr3pIuRpIiFaNWwF3yn/d0wFcHnlrMKg3HwAbyysmlCUy5fltE0Q5LqJ4qQgWVCs46DhiYAZ98lJdsfZVEykz7TP1VngOFs/enET6PL7Bpmmi20lV/7lafdFz+ysIb+tmY/5pr6MoccJWxEXv8kESi5PghdBsRdO9iSbrC+iyHJkiu1PB89PrbVXY2Aup30lvCf/K1ZW90BPG2yCXQbY2GghtrCqOe0F+/vY3U1a1dcsPBNjRBdWICqflq3ATsyC4f16D/1Qxa2JDBUDcxJ6e8TTIYJ4eDEneKuBKudyN/d/5iOp7dG+CqlLiB3S1oHoye5YHSNwthjbV6wOtp0lL8LoNzY7sHb8s+PE3UhKDTa3Ukg5Mei2ql5w5C6yPsPIhA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-creds
      namespace: nessie
